

<div class="form-group col-sm-4" >
    <input type="text" class="form-control" id="nome" placeholder="NOME">
    <input type="text" class="form-control" id="cognome" placeholder="COGNOME">
    <input type="text" class="form-control" id="email" placeholder="EMAIL">

    <input type="text" class="form-control" id="telefono" placeholder="TELEFONO">
    <br>
    <button type="button" class="btn col-sm-6" id="btn" > REGISTRATI</button>
</div>