<div class="container-fluid text-center">

    <div class=row>
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <h1>REGISTRAZIONE</h1>
        </div>
    </div>
    <br><br>

    <div class=row>
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="nome" placeholder="NOME">
            <br>
            <input type="text" class="form-control" id="cognome" placeholder="COGNOME">
            <br>
            <input type="text" class="form-control" id="cognome" placeholder="EMAIL">
            <br>
            <input type="text" class="form-control" id="cognome" placeholder="TELEFONO">
            <br>
            <button type="button" class="btn btn-primary" id="Registra">Login</button>
        </div>
    </div>

</div>

